itaw_api:
    resource: "@itawApiBundle/Resources/config/routing.yml"
    prefix:   /api

itaw_dns:
    resource: "@itawDnsBundle/Resources/config/routing.yml"
    prefix:   /

itaw_app:
    resource: "@itawAppBundle/Resources/config/routing.yml"
    prefix:   /config
    options:
        expose: true

_user_bundle:
    resource: "@itawUserBundle/Resources/config/routing.yml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"