itaw_dns:
    resource: "@itawDnsBundle/Resources/config/routing.yml"
    prefix:   /

itaw_app:
    resource: "@itawAppBundle/Resources/config/routing.yml"
    prefix:   /config

_user_bundle:
    resource: "@itawUserBundle/Resources/config/routing.yml"