security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        ajax_calls:
            pattern:    ^/(_(profiler|wdt)|css|images|js)/
            anonymous:  ~
        login_firewall:
            pattern:    ^/config/login$
            anonymous:  ~
        main:
            pattern: ^/config
            form_login:
                check_path: /config/login_check
                login_path: /config/login
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:
                path:   /config/logout
                target: /

    access_control:
        - { path: ^/config/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/config/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/config/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/config/admin/, role: ROLE_ADMIN }
        - { path: ^/_wdt, roles: 'IS_AUTHENTICATED_ANONYMOUSLY' }