accessors_collection:
    path:     /
    defaults: { _controller: itawAppBundle:Accessor:collection }

accessors_create:
    path:     /create
    defaults: { _controller: itawAppBundle:Accessor:create }

accessors_object:
    path:     /{accessorId}
    defaults: { _controller: itawAppBundle:Accessor:object }

accessors_delete:
    path:     /{accessorId}/delete
    defaults: { _controller: itawAppBundle:Accessor:delete }

accessors_toggle_active:
    path:     /{accessorId}/toggleActive
    defaults: { _controller: itawAppBundle:Accessor:toggleActive }

accessors_domains:
    resource: "@itawAppBundle/Resources/config/Accessor/Domain/routing.yml"
    prefix:   /{accessorId}/domains
